### ISSUE TITLE
Option to configure cloudwatch retention

### ISSUE THREAD

**Issue by BrandonWeng** [SPHTech-Platform/terraform-aws-opensearch#27]
We need the option to configure the retention for the cloudwatch log groups 

https://github.com/SPHTech-Platform/terraform-aws-opensearch/blob/main/cloudwatch.tf#L11

**Comment by abhinavkumarsph** [comment]
Opened a PR: https://github.com/SPHTech-Platform/terraform-aws-opensearch/pull/30

**Comment by abhinavkumarsph** [comment]
Included in `v1.2.0`: https://github.com/SPHTech-Platform/terraform-aws-opensearch/releases/tag/v1.2.0
